# CIRIS Agent Production Configuration
# This configuration is optimized for production deployment with enhanced security

version: "1.0"
log_level: "WARNING"  # Reduced logging for production

# Database Configuration - Production paths
database:
  db_filename: "/var/lib/ciris/ciris_engine.db"
  data_directory: "/var/lib/ciris/data"
  graph_memory_filename: "/var/lib/ciris/graph_memory.pkl"

# LLM Services Configuration
llm_services:
  openai:
    model_name: "gpt-4o"  # Production model
    base_url: null
    timeout_seconds: 45.0  # Increased timeout for production
    max_retries: 5  # More retries for production reliability
    api_key_env_var: "OPENAI_API_KEY"
    instructor_mode: "JSON"

# Workflow Processing Configuration - Conservative settings
workflow:
  max_active_tasks: 5  # Reduced for production stability
  max_active_thoughts: 25  # Reduced for production stability
  round_delay_seconds: 2.0  # Slower processing for stability
  max_rounds: 3  # Fewer rounds to prevent long processing times
  DMA_RETRY_LIMIT: 2  # Fewer retries for faster failure detection
  GUARDRAIL_RETRY_LIMIT: 1

# Enhanced Telemetry for Production Monitoring
telemetry:
  enabled: true  # Enabled for production monitoring
  internal_only: true
  retention_hours: 24  # Extended retention
  snapshot_interval_ms: 5000  # Less frequent for performance
  buffer_size: 2000  # Larger buffer for production
  security:
    require_tls: true
    require_auth: true
    pii_detection: true
    max_history_hours: 24
    encryption_key_env: "TELEMETRY_ENCRYPTION_KEY"
  collectors:
    instant:
      interval_ms: 100  # Slower for production
      max_buffer_size: 500
    fast:
      interval_ms: 1000
      max_buffer_size: 2000
    normal:
      interval_ms: 5000
      max_buffer_size: 5000
    slow:
      interval_ms: 30000
      max_buffer_size: 2000
    aggregate:
      interval_ms: 60000  # Hourly aggregation
      max_buffer_size: 500
  export:
    otlp: false
    websocket: false
    api: true  # API export for monitoring systems

# Enhanced Secrets Management
secrets:
  enabled: true
  storage:
    database_path: "/var/lib/ciris/secrets.db"
    encryption_key_env: "SECRETS_MASTER_KEY"
    key_rotation_days: 30  # More frequent rotation in production
  detection:
    builtin_patterns: true
    custom_patterns_enabled: true
    sensitivity_threshold: "HIGH"  # Higher sensitivity for production
  access_control:
    max_accesses_per_minute: 5  # Stricter limits
    max_accesses_per_hour: 50
    max_decryptions_per_hour: 10
    require_confirmation_for: ["HIGH", "CRITICAL"]  # More confirmation required
  audit:
    log_all_access: true
    log_path: "/var/log/ciris/secrets_audit.log"
    retention_days: 2555  # 7 years for compliance
  auto_decapsulation:
    enabled: true
    allowed_actions: ["speak", "tool"]  # Removed memorize for security
    require_purpose: true

# Conservative Resource Management
resources:
  enabled: true
  monitoring:
    interval_seconds: 5  # Less frequent monitoring
    history_hours: 48  # Extended history
  budgets:
    memory:
      limit: 128  # Lower limit for production stability
      warning: 100
      critical: 120
      action: "defer"
    cpu:
      limit: 60  # Conservative CPU limit
      warning: 40
      critical: 55
      action: "throttle"
    tokens_hour:
      limit: 5000  # Reduced for cost control
      warning: 4000
      critical: 4800
      action: "defer"
    tokens_day:
      limit: 50000  # Reduced for cost control
      warning: 40000
      critical: 48000
      action: "reject"
    thoughts:
      limit: 25  # Reduced for production stability
      warning: 20
      critical: 23
      action: "defer"
  actions:
    throttle:
      min_delay_seconds: 1.0  # Longer delays
      max_delay_seconds: 30.0
      increment: 2.0
    defer:
      priority_threshold: 70  # Higher priority threshold
    shutdown:
      grace_period_seconds: 60  # Longer grace period
      save_state: true

# Conservative Adaptive Configuration
adaptive:
  enabled: true
  filtering:
    new_user_threshold: 10  # Higher threshold for production
    sample_rate_default: 0.05  # Lower sampling rate
    effectiveness_threshold: 0.5  # Higher effectiveness required
    false_positive_threshold: 0.1  # Lower false positive tolerance
  learning:
    enabled: false  # Disabled for production stability
    adjustment_interval: 7200  # Longer intervals if enabled
    min_samples_for_adjustment: 50
  circuit_breaker:
    failure_threshold: 2  # Lower threshold for faster protection
    reset_timeout: 600  # Longer reset timeout
    half_open_test_interval: 120
  identity_updates:
    require_wa_approval: true
    wa_timeout_hours: 24  # Shorter timeout for production
    allow_emergency_override: false

# Enhanced Audit Configuration
audit:
  enable_signed_audit: true  # Enabled for production compliance
  enable_jsonl_audit: true
  audit_log_path: "/var/log/ciris/audit_logs.jsonl"
  audit_db_path: "/var/lib/ciris/ciris_audit.db"
  audit_key_path: "/etc/ciris/audit_keys"
  rotation_size_mb: 50  # Smaller files for easier management
  retention_days: 2555  # 7 years for compliance
  hash_chain:
    enabled: true
    algorithm: "sha256"
  signatures:
    enabled: true
    algorithm: "rsa-pss"
    key_size: 4096  # Stronger keys for production
    key_rotation_days: 30  # More frequent rotation
  anchoring:
    enabled: true
    interval_hours: 1
    method: "local"

# Enhanced Persistence Integrity
persistence:
  integrity:
    enabled: true
    mode: "full"
  hash_chains:
    tasks: true
    thoughts: true
    graph_nodes: true  # Enabled for production
  signatures:
    enabled: true
    selective: true
    deferred_thoughts: true
    high_priority_tasks: true
    wa_updates: true
  verification:
    on_startup: true  # Enabled for production
    on_deferral: true
    periodic_hours: 6  # More frequent verification

# Network Configuration
network:
  enabled_networks: ["cirisnode"]  # Only trusted networks
  agent_identity_path: "/etc/ciris/agent_identity.pem"
  peer_discovery_interval: 600  # Less frequent discovery
  reputation_threshold: 50  # Higher reputation requirement

# CIRISNode Configuration
cirisnode:
  base_url: "https://cirisnode.example.com:8001"
  timeout_seconds: 60.0  # Longer timeout for production
  max_retries: 3
  agent_secret_jwt: null  # Set via environment variable

# Wisdom-seeking Configuration
wisdom:
  wa_timeout_hours: 24  # Shorter timeout for production
  allow_universal_guidance: false  # Disabled for security
  minimum_urgency_for_universal: 95  # Very high threshold
  peer_consensus_threshold: 5  # Higher consensus requirement

# Agent Profile Configuration
profile_directory: "/etc/ciris/profiles"
default_profile: "production"
agent_profiles: {}

# Runtime Configuration
discord_channel_id: null  # Set via environment variable
agent_mode: "discord"  # Production mode
cli_channel_id: null
api_channel_id: null
data_archive_dir: "/var/lib/ciris/archive"
archive_older_than_hours: 12  # More frequent archiving