version: '3.8'
services:
  cirisagent:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PROFILE_NAME=teacher
        - MODE_LIST=discord,api
    env_file:
      - .env
    ports:
      - "8000:8000"  # Default API port
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: python main.py --modes discord,api --profile teacher --host 0.0.0.0 --port 8000