version: '3.8'
services:
  cirisagent_echo_core:
    container_name: echo-core
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PROFILE_NAME=echo-core
        - MODE_LIST=discord,api
    env_file:
      - .env.echo-core
    ports:
      - "8003:8003"  # Echo Core API port
    volumes:
      - ./vol/echo-core:/app/logs
      - ./vol/echo-core/data:/app/data
    command: python main.py --profile echo-core --modes discord,api --host 0.0.0.0 --port 8003
