version: '3.8'

services:
  # CIRIS with API and Discord adapters using mock LLM
  ciris-api-discord-mock:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ciris-api-discord-mock
    env_file:
      - ${CIRIS_ENV_FILE:-.env}
    environment:
      - CIRIS_MOCK_LLM=true
      # Discord configuration
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DISCORD_DEFERRAL_CHANNEL_ID=${DISCORD_DEFERRAL_CHANNEL_ID}
      - DISCORD_ADMIN_USER_IDS=${DISCORD_ADMIN_USER_IDS}
      - DISCORD_SNORE_CHANNEL_ID=${DISCORD_SNORE_CHANNEL_ID}
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    # Note: --host 0.0.0.0 is required in Docker containers to bind to all interfaces
    command: ["python", "main.py", "--adapter", "api", "--adapter", "discord", "--mock-llm", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s