version: '3.8'

services:
  ciris-local:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ciris-local
    ports:
      - "8080:8080"
    environment:
      # Force mock LLM
      - CIRIS_MOCK_LLM=true
      # API configuration
      - CIRIS_API_HOST=0.0.0.0
      - CIRIS_API_PORT=8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      # Mount the .env.datum file as .env in the container
      - ./.env.datum:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: ["python", "main.py", "--adapter", "api", "--adapter", "discord", "--mock-llm"]