version: '3.8'
services:
  cirisagent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command: python run_discord_teacher.py
