version: '3.8'

services:
  ciris-api-mock:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PROFILE_NAME: datum
        MODE_LIST: api
    container_name: ciris-api-mock
    environment:
      # Mock LLM mode
      CIRIS_MOCK_LLM: "true"
      
      # API Configuration
      CIRIS_API_HOST: "0.0.0.0"
      CIRIS_API_PORT: "8080"
      
      # Agent Configuration
      # Template and adapter are set via command line args
      
      # Logging
      CIRIS_LOG_LEVEL: INFO
      
      # Optional: Enable debug mode
      # CIRIS_DEBUG: "true"
      
    ports:
      - "8080:8080"
    
    volumes:
      # Mount logs directory for access to logs
      - ./logs:/app/logs
      # Mount data directory for persistence
      - ./data:/app/data
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Override the default command to use mock-llm flag
    command: ["python", "main.py", "--adapter", "api", "--template", "datum", "--mock-llm", "--host", "0.0.0.0", "--port", "8080"]