version: '3.8'
services:
  cirisagent_echo_spec:
    container_name: echo-speculative
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PROFILE_NAME=echo-speculative
        - MODE_LIST=discord,api
    env_file:
      - .env.echo-spec
    ports:
      - "8004:8004"  # Echo Speculative API port
    volumes:
      - ./vol/echo-speculative:/app/logs
      - ./vol/echo-speculative/data:/app/data
    command: python main.py --profile echo-speculative --modes discord,api --host 0.0.0.0 --port 8004
