"""Regression test: tools/generate_ios_secrets.py output must be byte-identical
to mobile/androidApp/build.gradle's `generatePythonSecrets` task output.

Why this exists:
The agent's `_build_secrets.py` is generated independently on iOS (Python
script) and Android (Gradle task). Both feed into the same runtime
integrity-check via BUILD_SECRETS_HASHES (in tools/ops/build_agent_extras.py).
If the two generators produce different bytes for the same input secrets, the
SHA-256 hash won't match on whichever platform built second, and the runtime
file-integrity guard will trip.

Pre-2.7.8.4 the iOS Python script and Android Gradle task drifted across
three byte-level differences (docstring, blank-line spacing, getter
spacing, EOF newline). This test pins the iOS-side output to match Android,
so any future drift fails CI before it reaches a build.

The test renders the iOS template with empty/known secrets, then asserts the
result against a hand-verified canonical Android-shaped string. If you change
either generator, regenerate the canonical and update this test.

Cannot test the live Gradle task from Python; we test the iOS side and pin
the canonical output that Android is documented to produce.
"""

import importlib.util
import sys
from pathlib import Path
from unittest.mock import patch


_MODULE_PATH = Path(__file__).resolve().parents[2] / "tools" / "generate_ios_secrets.py"
_spec = importlib.util.spec_from_file_location("generate_ios_secrets", _MODULE_PATH)
generate_ios_secrets = importlib.util.module_from_spec(_spec)
sys.modules["generate_ios_secrets"] = generate_ios_secrets
_spec.loader.exec_module(generate_ios_secrets)


# Canonical Android output for empty secrets, per mobile/androidApp/build.gradle
# `generatePythonSecrets` task. Hand-verified by rendering the Groovy template
# with empty secrets dicts. Any byte change to either generator breaks this
# test — that's the point.
EXPECTED_EMPTY_SECRETS_OUTPUT = '''"""
Build-time generated secrets - DO NOT EDIT OR COMMIT.
Generated by mobile/androidApp/build.gradle

Available functions:
  - get_arka_api_key()
  - get_coinbase_paymaster_url()
"""
from typing import Optional


def _deobfuscate(data: list, key: list) -> str:
    """Deobfuscate XOR-encoded data."""
    return \'\'.join(chr(d ^ key[i % len(key)]) for i, d in enumerate(data))


_XK = [0x5A, 0x3C, 0x7E, 0x1F, 0x9B, 0x4D, 0x2E, 0x6A]

def get_arka_api_key() -> str:
    """Get arka_api_key (obfuscated at build time)."""
    data = []
    if not data:
        return ""
    return _deobfuscate(data, _XK)


def get_coinbase_paymaster_url() -> str:
    """Get coinbase_paymaster_url (obfuscated at build time)."""
    data = []
    if not data:
        return ""
    return _deobfuscate(data, _XK)

'''


class TestGenerateIosSecretsAndroidParity:
    """The iOS generator's output must equal the Android Gradle task's
    output byte-for-byte. If either changes, both must change in lockstep
    or the runtime integrity check breaks for the platform that built second.
    """

    def test_empty_secrets_produces_canonical_output(self, tmp_path, monkeypatch):
        """When secrets files don't exist, getters produce empty data lists.
        The full file should match the Android-canonical shape exactly."""
        # Point the generator's SECRETS dict at non-existent files so all
        # secrets render as empty data lists (the deterministic test surface)
        monkeypatch.setattr(
            generate_ios_secrets,
            "SECRETS",
            {
                "arka_api_key": str(tmp_path / "nonexistent_etherspot"),
                "coinbase_paymaster_url": str(tmp_path / "nonexistent_paymaster"),
            },
        )

        # Run the generator, redirecting outputs to temp files so we can
        # inspect what it wrote.
        out1 = tmp_path / "ios_resources" / "ciris_adapters" / "wallet" / "providers" / "_build_secrets.py"
        out2 = tmp_path / "in_tree" / "ciris_adapters" / "wallet" / "providers" / "_build_secrets.py"
        monkeypatch.setattr(
            generate_ios_secrets,
            "main",
            _make_main_with_outputs(generate_ios_secrets, [out1, out2]),
        )
        # Run main(). Need to chdir to tmp_path so relative imports inside
        # the generator's main() don't trip if any.
        monkeypatch.chdir(tmp_path)
        generate_ios_secrets.main()

        assert out1.exists(), "iOS Resources output not written"
        assert out2.exists(), "in-tree output not written"

        actual = out1.read_text()
        # Must match Android byte-for-byte
        assert actual == EXPECTED_EMPTY_SECRETS_OUTPUT, _diff_msg(
            actual, EXPECTED_EMPTY_SECRETS_OUTPUT
        )

        # Both output paths must contain identical bytes (sanity)
        assert out1.read_bytes() == out2.read_bytes(), (
            "iOS Resources copy and in-tree copy diverged — they must be "
            "byte-identical (same generator, same call)"
        )

    def test_canonical_docstring_says_android(self):
        """Pin the docstring text that's load-bearing for Android-iOS parity.
        The canonical text says 'Generated by mobile/androidApp/build.gradle'
        on BOTH platforms. If iOS ever reverts to 'Generated by tools/...'
        this assertion catches it before the runtime hash check trips."""
        assert "Generated by mobile/androidApp/build.gradle" in EXPECTED_EMPTY_SECRETS_OUTPUT
        assert "Generated by tools/generate_ios_secrets.py" not in EXPECTED_EMPTY_SECRETS_OUTPUT

    def test_xor_key_uses_hex_literals_not_decimal(self):
        """Pin the _XK representation. Groovy's heredoc preserves the source
        characters '0x5A, 0x3C, ...' as a string literal (no interpolation).
        If the iOS Python generator ever interpolates the key as a list of
        ints (which Python repr would render as '[90, 60, ...]'), the docstring
        differs by representation while the values are equal — and the
        SHA-256 differs."""
        assert "_XK = [0x5A, 0x3C, 0x7E, 0x1F, 0x9B, 0x4D, 0x2E, 0x6A]" in EXPECTED_EMPTY_SECRETS_OUTPUT
        assert "_XK = [90, 60, 126, 31, 155, 77, 46, 106]" not in EXPECTED_EMPTY_SECRETS_OUTPUT


def _make_main_with_outputs(module, outputs):
    """Wrap the generator's main() so it writes to test paths instead of
    the in-tree paths."""
    def patched_main():
        # Re-run the body of generate_ios_secrets.main() but with our outputs.
        # The body is small enough we just inline it here.
        from pathlib import Path

        obfuscated = {}
        for name, filepath in module.SECRETS.items():
            p = Path(filepath)
            if p.exists():
                value = p.read_text().strip()
                obfuscated[name] = module.obfuscate(value)
            else:
                obfuscated[name] = []

        getters = []
        for name, data in obfuscated.items():
            getters.append(
                f'''
def get_{name}() -> str:
    """Get {name} (obfuscated at build time)."""
    data = {data}
    if not data:
        return ""
    return _deobfuscate(data, _XK)
'''
            )

        available = "\n".join(f"  - get_{name}()" for name in obfuscated)
        content = f'''"""
Build-time generated secrets - DO NOT EDIT OR COMMIT.
Generated by mobile/androidApp/build.gradle

Available functions:
{available}
"""
from typing import Optional


def _deobfuscate(data: list, key: list) -> str:
    """Deobfuscate XOR-encoded data."""
    return \'\'.join(chr(d ^ key[i % len(key)]) for i, d in enumerate(data))


_XK = [0x5A, 0x3C, 0x7E, 0x1F, 0x9B, 0x4D, 0x2E, 0x6A]
{"\n".join(getters)}
'''
        for out in outputs:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content)

    return patched_main


def _diff_msg(actual: str, expected: str) -> str:
    import difflib
    diff = "\n".join(
        difflib.unified_diff(
            expected.splitlines(keepends=False),
            actual.splitlines(keepends=False),
            fromfile="expected (Android-canonical)",
            tofile="actual (iOS generator)",
            lineterm="",
        )
    )
    return f"iOS generator output drifted from Android canonical:\n{diff}"
