import SwiftUI
import shared

struct ContentView: View {
    @State private var pythonReady = false
    @State private var initError: String? = nil

    var body: some View {
        if pythonReady {
            // Show the Compose UI with Apple Sign-In support once Python is ready
            ComposeViewWithAuth()
                .ignoresSafeArea()
        } else if let error = initError {
            // Show error state
            ErrorView(message: error) {
                // Retry
                initError = nil
                Task {
                    await initializePython()
                }
            }
        } else {
            // Show loading while initializing Python
            InitializingView()
                .task {
                    await initializePython()
                }
        }
    }

    private func initializePython() async {
        NSLog("[ContentView] Starting Python initialization...")

        // Initialize Python interpreter
        let success = PythonBridge.initializePython()
        if !success {
            initError = "Failed to initialize Python interpreter"
            return
        }

        // Start the CIRIS runtime
        let started = PythonBridge.startRuntime()
        if !started {
            initError = "Failed to start CIRIS runtime"
            return
        }

        // Wait for server to be ready (poll health endpoint)
        var attempts = 0
        let maxAttempts = 30  // 30 seconds max

        while attempts < maxAttempts {
            try? await Task.sleep(nanoseconds: 1_000_000_000)  // 1 second
            attempts += 1

            if PythonBridge.checkHealth() {
                NSLog("[ContentView] Server is healthy after \(attempts) seconds")
                await MainActor.run {
                    pythonReady = true
                }
                return
            }

            NSLog("[ContentView] Waiting for server... (\(attempts)/\(maxAttempts))")
        }

        initError = "Server did not become healthy within 30 seconds"
    }
}

// MARK: - Initializing View

struct InitializingView: View {
    var body: some View {
        ZStack {
            Color(red: 0.1, green: 0.1, blue: 0.18)
                .ignoresSafeArea()

            VStack(spacing: 24) {
                Image(systemName: "brain.head.profile")
                    .font(.system(size: 80))
                    .foregroundColor(Color(red: 0.255, green: 0.612, blue: 0.627))

                Text("CIRIS")
                    .font(.system(size: 36, weight: .bold, design: .rounded))
                    .foregroundColor(.white)

                Text("Initializing Python runtime...")
                    .font(.system(size: 14))
                    .foregroundColor(.gray)

                ProgressView()
                    .progressViewStyle(CircularProgressViewStyle(tint: Color(red: 0, green: 0.83, blue: 1)))
                    .scaleEffect(1.5)
            }
        }
    }
}

// MARK: - Error View

struct ErrorView: View {
    let message: String
    let onRetry: () -> Void

    var body: some View {
        ZStack {
            Color(red: 0.1, green: 0.1, blue: 0.18)
                .ignoresSafeArea()

            VStack(spacing: 24) {
                Image(systemName: "exclamationmark.triangle")
                    .font(.system(size: 60))
                    .foregroundColor(.red)

                Text("Initialization Error")
                    .font(.system(size: 24, weight: .bold))
                    .foregroundColor(.white)

                Text(message)
                    .font(.system(size: 14))
                    .foregroundColor(.gray)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal)

                Button(action: onRetry) {
                    Text("Retry")
                        .foregroundColor(.white)
                        .padding(.horizontal, 32)
                        .padding(.vertical, 12)
                        .background(Color(red: 0.255, green: 0.612, blue: 0.627))
                        .cornerRadius(8)
                }
            }
        }
    }
}

// MARK: - Compose Multiplatform Integration

struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewController is generated by KMP from shared module
        return Main_iosKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

/// Compose view with Apple Sign-In integration
struct ComposeViewWithAuth: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        NSLog("[ComposeViewWithAuth] makeUIViewController called - setting up Apple Sign-In callbacks")

        // Get the key window for presenting the Apple Sign-In sheet
        let scenes = UIApplication.shared.connectedScenes
        let windowScene = scenes.first as? UIWindowScene
        let keyWindow = windowScene?.windows.first { $0.isKeyWindow }

        NSLog("[ComposeViewWithAuth] keyWindow: \(String(describing: keyWindow))")

        let vc = Main_iosKt.MainViewControllerWithAuth(
            onAppleSignInRequested: { callback in
                NSLog("[ComposeViewWithAuth] onAppleSignInRequested LAMBDA INVOKED - about to call AppleSignInHelper.signIn")

                AppleSignInHelper.shared.signIn(presentingWindow: keyWindow) { result in
                    switch result {
                    case .success(let credential):
                        NSLog("[ComposeViewWithAuth] Apple Sign-In success")
                        let bridgeResult = AppleSignInResultBridge.companion.success(
                            idToken: credential.idToken,
                            userId: credential.userId,
                            email: credential.email,
                            displayName: credential.fullName
                        )
                        callback(bridgeResult)

                    case .failure(let error):
                        NSLog("[ComposeViewWithAuth] Apple Sign-In error: \(error.localizedDescription)")
                        if let appleError = error as? AppleSignInHelper.AppleSignInError,
                           appleError == .cancelled {
                            callback(AppleSignInResultBridge.companion.cancelled())
                        } else {
                            callback(AppleSignInResultBridge.companion.error(message: error.localizedDescription))
                        }
                    }
                }
            },
            onSilentSignInRequested: { callback in
                NSLog("[ComposeViewWithAuth] onSilentSignInRequested LAMBDA INVOKED")

                AppleSignInHelper.shared.silentSignIn { result in
                    switch result {
                    case .success(let credential):
                        NSLog("[ComposeViewWithAuth] Silent sign-in success")
                        let bridgeResult = AppleSignInResultBridge.companion.success(
                            idToken: credential.idToken,
                            userId: credential.userId,
                            email: credential.email,
                            displayName: credential.fullName
                        )
                        callback(bridgeResult)

                    case .failure(let error):
                        NSLog("[ComposeViewWithAuth] Silent sign-in not available: \(error.localizedDescription)")
                        // For silent sign-in failures, we return an error to indicate sign-in is required
                        callback(AppleSignInResultBridge.companion.error(message: "4: SIGN_IN_REQUIRED"))
                    }
                }
            }
        )

        NSLog("[ComposeViewWithAuth] MainViewControllerWithAuth returned VC: \(vc)")
        return vc
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        NSLog("[ComposeViewWithAuth] updateUIViewController called")
    }
}

#Preview {
    ContentView()
}
