"""29-language × every-prompt-template harness for unexpanded-placeholder detection.

Why this exists
===============
Prompt templates use Python `.format(**kwargs)` to inject runtime context.
When the template references a variable that the caller doesn't pass — e.g.
because a schema reshape removed the field, or a locale translator left a
stale `{stakeholders}` placeholder, or a YAML author typoed `{user_id}` as
`{userid}` — Python's format() raises KeyError on STRICT missing keys but
silently leaves the literal `{var}` token in the rendered string for the
LLM-permissive paths.

The LLM then receives a malformed prompt with literal placeholder tokens
and produces degraded output with no error signal. This bug class is
historically silent and easy to miss in code review.

What this test does
===================
For each (template_name × locale) combination across 29 locales:

1. Load the prompt via the appropriate loader (DMA or conscience). The
   loader internally calls `safe_format` which DETECTS unexpanded
   placeholders and (in strict mode) RAISES.
2. Format the result with a kitchen-sink kwargs fixture that mirrors what
   the runtime evaluators actually pass.
3. Strict mode is enforced via `CIRIS_STRICT_PROMPT_FORMAT=1`, set by an
   autouse fixture so any leftover `{identifier}` becomes a hard test
   failure.

Runs in parallel via pytest-xdist (29 locales × ~7 templates ≈ 200 cases).

What it catches
===============
- Schema reshapes that drop fields the templates still reference
- YAML translator drift (e.g. ja translator left {user_message} as
  {user_msg} in their copy)
- Missing kwargs at evaluator call sites
- Polyglot block author leaving `{POLYGLOT_*}` markers ungutted
- Stale field names like {stakeholders} from pre-v3.2 PDMA shape
"""
from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Dict, List, Tuple

import pytest

# Strict mode MUST be set before any prompt loader imports so the module-level
# safe_format check picks it up. Module-level autouse fixture handles per-test;
# this conftest-equivalent set is for import-time safety.
os.environ.setdefault("CIRIS_STRICT_PROMPT_FORMAT", "1")

from ciris_engine.logic.dma.prompt_loader import (  # noqa: E402
    UNEXPANDED_PLACEHOLDER_PATTERN,
    DMAPromptLoader,
    safe_format,
)

# All 29 locales (en master + 28 translations). Source of truth lives in
# localization/manifest.json; this hardcoded list is the test harness's
# tripwire — if a locale gets added/removed, this test will surface that
# the prompt directories are out of sync.
ALL_LOCALES = [
    "am", "ar", "bn", "de", "en", "es", "fa", "fr", "ha", "hi",
    "id", "it", "ja", "ko", "mr", "my", "pa", "pt", "ru", "sw",
    "ta", "te", "th", "tr", "uk", "ur", "vi", "yo", "zh",
]

# Every DMA prompt template the runtime can load. Order matches
# `ciris_engine/logic/dma/prompts/*.yml`.
DMA_TEMPLATES = [
    "pdma_ethical",
    "csdma_common_sense",
    "dsdma_base",
    "idma",
    "action_selection_pdma",
    "tsaspdma",
    "dsaspdma",
]

# Every kwarg the DMA evaluators are known to pass to .format(). Kitchen-sink
# fixture: any one DMA only uses a subset, but providing the union means we
# never get a false-positive KeyError for missing kwargs while the test runs.
#
# This list is the AUTHORITATIVE inventory of placeholders the templates may
# reference. Any new placeholder MUST be added here AND wired through the
# evaluator's `.format()` call site at the same time — the
# `test_dma_yaml_placeholders_in_known_kwargs` test refuses any unlisted
# placeholder. Catches the silent N/A regression where a template references
# a field the call site doesn't supply.
#
# Inventory generated by walking every (locale, template) pair across 29
# locales and 7 DMA templates. As of v3.2: 14 unique identifiers.
DMA_FORMAT_KWARGS: Dict[str, Any] = {
    # Core DMA context (every DMA passes these)
    "full_context_str": "[test fixture] system_snapshot + user_profiles context block",
    "original_thought_content": "[test fixture] thought content under evaluation",
    "context_summary": "[test fixture] high-level context summary",
    # IDMA specific
    "prior_dma_context": "[test fixture] prior DMA results (PDMA + CSDMA + DSDMA)",
    # ASPDMA / TSASPDMA / DSASPDMA specific
    "aspdma_reasoning": "[test fixture] aspdma reasoning trace",
    "context_enrichment_section": "[test fixture] context enrichment block",
    "tool_documentation": "[test fixture] tool documentation block",
    "tool_name": "[test fixture] tool name",
    # DSASPDMA (deferral-specific)
    "current_context": "[test fixture] current deferral context",
    "current_defer_until": "[test fixture] current defer-until time",
    "current_domain_hint": "[test fixture] current domain hint",
    "current_reason": "[test fixture] current deferral reason",
    "domain_hint_options": "[test fixture] domain hint enum options",
    "taxonomy_text": "[test fixture] DSASPDMA taxonomy text",
    # DSDMA-specific (passed by dsdma_base.py:331-339 .format() call)
    "domain_name": "test_domain",
    "rules_summary_str": "[test fixture] domain rules summary",
    "context_str": "[test fixture] platform context",
    "identity_block": "[test fixture] identity block",
    "task_history_block": "[test fixture] task history block",
    "escalation_guidance_block": "[test fixture] escalation guidance",
    "system_snapshot_block": "[test fixture] system snapshot block",
    "user_profiles_block": "[test fixture] user profiles block",
    "crisis_resources_block": "[test fixture] crisis resources",
}

# Conscience prompt names. Loaded via the conscience-specific loader.
CONSCIENCE_TEMPLATES = [
    "entropy_conscience",
    "coherence_conscience",
    "optimization_veto_conscience",
    "epistemic_humility_conscience",
]


@pytest.fixture(autouse=True)
def _strict_prompt_format_mode(monkeypatch: pytest.MonkeyPatch) -> None:
    """Force strict mode for every test: leftover {placeholder} → ValueError."""
    monkeypatch.setenv("CIRIS_STRICT_PROMPT_FORMAT", "1")


def _expected_yaml_path(template_name: str, locale: str) -> Path:
    """Return where a (template, locale) pair lives on disk.

    English (`en`) lives in the master prompts/ directory; every other locale
    lives under prompts/localized/<lang>/. Returning a Path doesn't validate
    that the file exists — callers handle the missing-locale case explicitly
    (some prompts may not be translated for every locale).
    """
    base = Path(__file__).resolve().parent.parent / "ciris_engine" / "logic" / "dma" / "prompts"
    if locale == "en":
        return base / f"{template_name}.yml"
    return base / "localized" / locale / f"{template_name}.yml"


def _conscience_yaml_path(template_name: str, locale: str) -> Path:
    """Same idea for conscience prompts."""
    base = Path(__file__).resolve().parent.parent / "ciris_engine" / "logic" / "conscience" / "prompts"
    if locale == "en":
        return base / f"{template_name}.yml"
    return base / "localized" / locale / f"{template_name}.yml"


# ──────────────────────────────────────────────────────────────────
# Test 1: safe_format detects leftover placeholders (unit-level)
# ──────────────────────────────────────────────────────────────────


class TestSafeFormat:
    def test_clean_format_returns_rendered(self) -> None:
        """Happy path: all placeholders substituted, returns formatted string."""
        result = safe_format("Hello {name}", source="test", name="world")
        assert result == "Hello world"

    def test_strict_mode_raises_on_leftover(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """Strict mode raises ValueError when leftovers survive .format().

        Use `{{absent}}` (double-brace escape) so .format() doesn't KeyError
        — it's the *post-format* leftover detection we're testing here, not
        the *missing-kwarg* path which Python handles natively.
        """
        monkeypatch.setenv("CIRIS_STRICT_PROMPT_FORMAT", "1")
        with pytest.raises(ValueError, match=r"Unexpanded placeholders.*\['\{absent\}'\]"):
            safe_format("Hello {name}, age {{absent}}", source="test_template", name="world")

    def test_production_mode_warns_on_leftover(self, monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture) -> None:
        """Production mode (env unset) logs WARNING and returns the malformed string."""
        monkeypatch.delenv("CIRIS_STRICT_PROMPT_FORMAT", raising=False)
        with caplog.at_level("WARNING"):
            # Simulate the cross-package call: format() with extra placeholder
            template = "Hello {name}, age {absent}"
            # `.format(name="world")` would KeyError on `absent`. To exercise
            # the leftover path we use a template where {{absent}} (escaped)
            # becomes literal {absent} in the output:
            result = safe_format("Hello {name}, age {{absent}}", source="prod_test", name="world")
        assert result == "Hello world, age {absent}"
        assert any("Unexpanded placeholders" in rec.message for rec in caplog.records)
        assert any("{absent}" in rec.message for rec in caplog.records)

    def test_json_examples_dont_falsely_match(self) -> None:
        """JSON examples like {"key": "val"} must NOT trip the detector."""
        # JSON example after format() escape-resolution becomes single-brace.
        # The pattern matches identifier-only placeholders, not JSON.
        result = safe_format(
            'Reply as: {{"action": "speak"}}\nUser: {name}',
            source="json_test",
            name="alice",
        )
        assert result == 'Reply as: {"action": "speak"}\nUser: alice'

    def test_action_verb_set_doesnt_match(self) -> None:
        """Lists like {speak, defer, observe} (with commas) must not match the
        identifier-only pattern."""
        # Use {{}} to escape so .format doesn't try to expand
        result = safe_format(
            "Choose from: {{speak, defer, observe}}",
            source="set_test",
        )
        # The output has literal {speak, defer, observe} which contains a comma
        # — the regex requires identifier characters only inside braces.
        leftovers = UNEXPANDED_PLACEHOLDER_PATTERN.findall(result)
        assert leftovers == []


# ──────────────────────────────────────────────────────────────────
# Test 2: 29-locale × every-DMA-template parallel sweep
# ──────────────────────────────────────────────────────────────────


def _gen_dma_param_ids() -> List[Tuple[str, str]]:
    """Generate (locale, template_name) pairs that have an actual YAML on disk."""
    pairs = []
    for locale in ALL_LOCALES:
        for tmpl in DMA_TEMPLATES:
            yaml_path = _expected_yaml_path(tmpl, locale)
            if yaml_path.is_file():
                pairs.append((locale, tmpl))
    return pairs


@pytest.mark.parametrize(
    ("locale", "template_name"),
    _gen_dma_param_ids(),
    ids=lambda v: v,
)
def test_dma_prompt_format_safety(locale: str, template_name: str) -> None:
    """Every DMA template × every locale must format with kitchen-sink kwargs
    and emit zero unexpanded `{identifier}` placeholders.

    Strict mode (autouse fixture) makes leftover placeholders raise ValueError
    out of safe_format inside the loader's get_system_message and
    get_user_message paths.
    """
    loader = DMAPromptLoader(language=locale)
    collection = loader.load_prompt_template(template_name)

    # System message: exercises every formattable system field
    system = loader.get_system_message(collection, **DMA_FORMAT_KWARGS)
    leftovers = sorted(set(UNEXPANDED_PLACEHOLDER_PATTERN.findall(system)))
    assert not leftovers, (
        f"DMA[{locale}/{template_name}] system message has unexpanded "
        f"placeholders after .format(): {leftovers}. Either the template "
        f"references a stale field name, the locale translator left an "
        f"untranslated marker, or DMA_FORMAT_KWARGS in this test is missing "
        f"a kwarg the runtime actually passes."
    )

    # User message: exercises context_integration
    user = loader.get_user_message(collection, **DMA_FORMAT_KWARGS)
    leftovers = sorted(set(UNEXPANDED_PLACEHOLDER_PATTERN.findall(user)))
    assert not leftovers, (
        f"DMA[{locale}/{template_name}] user message has unexpanded "
        f"placeholders after .format(): {leftovers}."
    )


# ──────────────────────────────────────────────────────────────────
# Test 3: YAML-walk lint (catches issues at template-author time)
# ──────────────────────────────────────────────────────────────────


def _resolved_template_placeholders(loader: DMAPromptLoader, template_name: str) -> List[str]:
    """Extract every `{identifier}` placeholder from a template AFTER polyglot
    substitution but BEFORE .format(). Walks every formattable string field on
    the PromptCollection, escapes legitimate JSON-example double-braces (which
    get unescaped only at .format() time), and applies the identifier-only
    pattern.

    Why post-polyglot: the raw YAML contains `{{POLYGLOT_PDMA_FRAMING}}` which
    the regex would (correctly) match the inner `{POLYGLOT_PDMA_FRAMING}` of —
    but that's a load-time substitution marker, not a format-time placeholder.
    Running the check after polyglot expansion eliminates that false positive
    while still surfacing real format-time stale references.

    Why pre-format: we want to validate what the TEMPLATE author intended.
    Post-format would give us the rendered string, but we already have a
    runtime-rendered test for that (test_dma_prompt_format_safety).
    """
    collection = loader.load_prompt_template(template_name)
    placeholders: set[str] = set()
    for field in (
        "system_guidance_header",
        "domain_principles",
        "evaluation_steps",
        "evaluation_criteria",
        "response_format",
        "response_guidance",
        "context_integration",
    ):
        text = getattr(collection, field, None)
        if not text:
            continue
        # Strip {{...}} (legitimate JSON-example escapes) before the identifier
        # match so we don't double-count their inner content.
        sanitized = re.sub(r"\{\{[^{}]*\}\}", "", text)
        placeholders.update(UNEXPANDED_PLACEHOLDER_PATTERN.findall(sanitized))
    return sorted(placeholders)


@pytest.mark.parametrize(
    ("locale", "template_name"),
    _gen_dma_param_ids(),
    ids=lambda v: v,
)
def test_dma_yaml_placeholders_in_known_kwargs(locale: str, template_name: str) -> None:
    """Every `{identifier}` placeholder appearing in any resolved DMA template
    must be in DMA_FORMAT_KWARGS. New placeholders require BOTH the template
    AND the fixture to be updated together — preventing the silent N/A
    regression where a template references a field but the call site doesn't
    supply it.
    """
    loader = DMAPromptLoader(language=locale)
    placeholders = _resolved_template_placeholders(loader, template_name)
    unknown = [p for p in placeholders if p.strip("{}") not in DMA_FORMAT_KWARGS]
    assert not unknown, (
        f"DMA[{locale}/{template_name}] references placeholders not in "
        f"DMA_FORMAT_KWARGS: {unknown}. Either add them to the kitchen-sink "
        f"fixture (and wire them through the evaluator's .format() call) "
        f"OR remove them from the template."
    )
