/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Adapter configuration.
 *
 * @param id Adapter ID (api, cli, discord, reddit)
 * @param name Display name
 * @param description Adapter description
 * @param enabledByDefault Whether enabled by default
 * @param requiredEnvVars Required environment variables
 * @param optionalEnvVars Optional environment variables
 * @param platformRequirements Platform requirements (e.g., 'android_play_integrity')
 * @param platformAvailable Whether available on current platform
 */
@Serializable

data class AdapterConfig (

    /* Adapter ID (api, cli, discord, reddit) */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Display name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Adapter description */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* Whether enabled by default */
    @SerialName(value = "enabled_by_default") val enabledByDefault: kotlin.Boolean? = false,

    /* Required environment variables */
    @SerialName(value = "required_env_vars") val requiredEnvVars: kotlin.collections.List<kotlin.String>? = null,

    /* Optional environment variables */
    @SerialName(value = "optional_env_vars") val optionalEnvVars: kotlin.collections.List<kotlin.String>? = null,

    /* Platform requirements (e.g., 'android_play_integrity') */
    @SerialName(value = "platform_requirements") val platformRequirements: kotlin.collections.List<kotlin.String>? = null,

    /* Whether available on current platform */
    @SerialName(value = "platform_available") val platformAvailable: kotlin.Boolean? = true

) {


}
