/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.ConfigNodeAttributes
import ai.ciris.api.models.GraphNodeAttributes
import ai.ciris.api.models.LogNodeAttributes
import ai.ciris.api.models.MemoryNodeAttributes
import ai.ciris.api.models.NodeAttributesBase
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue
import ai.ciris.api.models.TelemetryNodeAttributes

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Node attributes
 *
 * @param createdBy Who created this node
 * @param content
 * @param memoryType Type: fact, experience, learning, insight, observation
 * @param source Where this memory originated
 * @param key Configuration key (unique within scope)
 * @param `value` Numeric value of the metric
 * @param description What this configuration controls
 * @param category Category: system, behavioral, ethical, operational
 * @param valueType Expected type: string, integer, float, boolean, list, dict
 * @param metricName Name of the metric
 * @param metricType Type: counter, gauge, histogram, summary
 * @param startTime Start of measurement period
 * @param endTime End of measurement period
 * @param durationSeconds Duration of measurement period
 * @param serviceName Service that generated this metric
 * @param logMessage The log message content
 * @param logLevel Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
 * @param createdAt
 * @param updatedAt
 * @param updatedBy
 * @param tags Tags for categorization
 * @param version Schema version for migration support
 * @param secretRefs Secret reference UUIDs for encrypted data
 * @param contentType Type of content: text, embedding, reference
 * @param importance Importance score from 0.0 to 1.0
 * @param confidence Confidence in this memory from 0.0 to 1.0
 * @param sourceType Source type: internal, user, system, external
 * @param channelId
 * @param userId
 * @param taskId
 * @param accessCount Number of times accessed
 * @param lastAccessed
 * @param relatedMemories IDs of related memory nodes
 * @param derivedFrom
 * @param embeddingModel
 * @param embeddingDimensions
 * @param validationRules Validation rules for this config
 * @param isSensitive Whether this contains sensitive data
 * @param requiresAuthority Whether changes require WiseAuthority approval
 * @param previousValue Previous value before last update
 * @param changeReason
 * @param approvedBy
 * @param scope Scope: system, channel, user
 * @param appliesTo Specific entities this applies to
 * @param isActive Whether this config is currently active
 * @param expiresAt
 * @param unit
 * @param aggregationType
 * @param sampleCount Number of samples in this metric
 * @param minValue
 * @param maxValue
 * @param meanValue
 * @param stdDeviation
 * @param percentiles Percentile values (e.g., p50, p95, p99)
 * @param labels Metric labels for filtering and grouping
 * @param host
 * @param warningThreshold
 * @param criticalThreshold
 * @param thresholdDirection
 * @param resourceType
 * @param resourceLimit
 * @param logTags Additional tags for the log entry
 * @param retentionPolicy Retention policy for this log
 */
@Serializable

data class Attributes (

    /* Who created this node */
    @SerialName(value = "created_by") @Required val createdBy: kotlin.String,

    @SerialName(value = "content") @Required val content: kotlin.String,

    /* Type: fact, experience, learning, insight, observation */
    @SerialName(value = "memory_type") @Required val memoryType: kotlin.String,

    /* Where this memory originated */
    @SerialName(value = "source") @Required val source: kotlin.String,

    /* Configuration key (unique within scope) */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* Numeric value of the metric */
    @SerialName(value = "value") @Required val `value`: kotlin.Double,

    /* What this configuration controls */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* Category: system, behavioral, ethical, operational */
    @SerialName(value = "category") @Required val category: kotlin.String,

    /* Expected type: string, integer, float, boolean, list, dict */
    @SerialName(value = "value_type") @Required val valueType: kotlin.String,

    /* Name of the metric */
    @SerialName(value = "metric_name") @Required val metricName: kotlin.String,

    /* Type: counter, gauge, histogram, summary */
    @SerialName(value = "metric_type") @Required val metricType: kotlin.String,

    /* Start of measurement period */
    @SerialName(value = "start_time") @Required val startTime: kotlinx.datetime.Instant,

    /* End of measurement period */
    @SerialName(value = "end_time") @Required val endTime: kotlinx.datetime.Instant,

    /* Duration of measurement period */
    @SerialName(value = "duration_seconds") @Required val durationSeconds: kotlin.Double,

    /* Service that generated this metric */
    @SerialName(value = "service_name") @Required val serviceName: kotlin.String,

    /* The log message content */
    @SerialName(value = "log_message") @Required val logMessage: kotlin.String,

    /* Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL */
    @SerialName(value = "log_level") @Required val logLevel: kotlin.String,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "updated_by") val updatedBy: kotlin.String? = null,

    /* Tags for categorization */
    @SerialName(value = "tags") val tags: kotlin.collections.List<kotlin.String>? = null,

    /* Schema version for migration support */
    @SerialName(value = "version") val version: kotlin.Int? = 1,

    /* Secret reference UUIDs for encrypted data */
    @SerialName(value = "secret_refs") val secretRefs: kotlin.collections.List<kotlin.String>? = null,

    /* Type of content: text, embedding, reference */
    @SerialName(value = "content_type") val contentType: kotlin.String? = "text",

    /* Importance score from 0.0 to 1.0 */
    @SerialName(value = "importance") val importance: kotlin.Double? = (0.5).toDouble(),

    /* Confidence in this memory from 0.0 to 1.0 */
    @SerialName(value = "confidence") val confidence: kotlin.Double? = (1.0).toDouble(),

    /* Source type: internal, user, system, external */
    @SerialName(value = "source_type") val sourceType: kotlin.String? = "internal",

    @SerialName(value = "channel_id") val channelId: kotlin.String? = null,

    @SerialName(value = "user_id") val userId: kotlin.String? = null,

    @SerialName(value = "task_id") val taskId: kotlin.String? = null,

    /* Number of times accessed */
    @SerialName(value = "access_count") val accessCount: kotlin.Int? = 0,

    @SerialName(value = "last_accessed") val lastAccessed: kotlinx.datetime.Instant? = null,

    /* IDs of related memory nodes */
    @SerialName(value = "related_memories") val relatedMemories: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "derived_from") val derivedFrom: kotlin.String? = null,

    @SerialName(value = "embedding_model") val embeddingModel: kotlin.String? = null,

    @SerialName(value = "embedding_dimensions") val embeddingDimensions: kotlin.Int? = null,

    /* Validation rules for this config */
    @SerialName(value = "validation_rules") val validationRules: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>>? = null,

    /* Whether this contains sensitive data */
    @SerialName(value = "is_sensitive") val isSensitive: kotlin.Boolean? = false,

    /* Whether changes require WiseAuthority approval */
    @SerialName(value = "requires_authority") val requiresAuthority: kotlin.Boolean? = false,

    /* Previous value before last update */
    @SerialName(value = "previous_value") val previousValue: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "change_reason") val changeReason: kotlin.String? = null,

    @SerialName(value = "approved_by") val approvedBy: kotlin.String? = null,

    /* Scope: system, channel, user */
    @SerialName(value = "scope") val scope: kotlin.String? = "system",

    /* Specific entities this applies to */
    @SerialName(value = "applies_to") val appliesTo: kotlin.collections.List<kotlin.String>? = null,

    /* Whether this config is currently active */
    @SerialName(value = "is_active") val isActive: kotlin.Boolean? = true,

    @SerialName(value = "expires_at") val expiresAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "unit") val unit: kotlin.String? = null,

    @SerialName(value = "aggregation_type") val aggregationType: kotlin.String? = null,

    /* Number of samples in this metric */
    @SerialName(value = "sample_count") val sampleCount: kotlin.Int? = 1,

    @SerialName(value = "min_value") val minValue: kotlin.Double? = null,

    @SerialName(value = "max_value") val maxValue: kotlin.Double? = null,

    @SerialName(value = "mean_value") val meanValue: kotlin.Double? = null,

    @SerialName(value = "std_deviation") val stdDeviation: kotlin.Double? = null,

    /* Percentile values (e.g., p50, p95, p99) */
    @SerialName(value = "percentiles") val percentiles: kotlin.collections.Map<kotlin.String, kotlin.Double>? = null,

    /* Metric labels for filtering and grouping */
    @SerialName(value = "labels") val labels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "host") val host: kotlin.String? = null,

    @SerialName(value = "warning_threshold") val warningThreshold: kotlin.Double? = null,

    @SerialName(value = "critical_threshold") val criticalThreshold: kotlin.Double? = null,

    @SerialName(value = "threshold_direction") val thresholdDirection: kotlin.String? = null,

    @SerialName(value = "resource_type") val resourceType: kotlin.String? = null,

    @SerialName(value = "resource_limit") val resourceLimit: kotlin.Double? = null,

    /* Additional tags for the log entry */
    @SerialName(value = "log_tags") val logTags: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Retention policy for this log */
    @SerialName(value = "retention_policy") val retentionPolicy: kotlin.String? = "raw"

) {


}
