name: iosApp
options:
  bundleIdPrefix: ai.ciris
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "**/.DS_Store"
      # Resources temporarily disabled - see prepare_python_bundle.sh
      # - path: Resources
      #   type: folder
      #   buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.ciris.mobile
        INFOPLIST_FILE: iosApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/../shared/build/bin/iosSimulatorArm64/debugFramework
          - $(PROJECT_DIR)/Frameworks
        HEADER_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Frameworks/Python.xcframework/ios-arm64_x86_64-simulator/Python.framework/Headers
        SWIFT_OBJC_BRIDGING_HEADER: iosApp/iosApp-Bridging-Header.h
        CLANG_ENABLE_MODULES: YES
    dependencies:
      - framework: ../shared/build/bin/iosSimulatorArm64/debugFramework/shared.framework
        embed: true
      - framework: Frameworks/Python.xcframework
        embed: true

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
