name: iosApp
options:
  bundleIdPrefix: ai.ciris
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: "${DEVELOPMENT_TEAM}"
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

configs:
  Debug:
    SWIFT_OPTIMIZATION_LEVEL: "-Onone"
  Release:
    SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "**/.DS_Store"
      # Resources bundled as zip to avoid code signing issues with 5000+ files
      - path: Resources.zip
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.ciris.mobile
        INFOPLIST_FILE: iosApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        CODE_SIGN_ENTITLEMENTS: iosApp/iosApp.entitlements
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
        SWIFT_OBJC_BRIDGING_HEADER: iosApp/iosApp-Bridging-Header.h
        CLANG_ENABLE_MODULES: YES
      configs:
        Debug:
          FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/../shared/build/bin/iosArm64/debugFramework
            - $(PROJECT_DIR)/Frameworks
          FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/../shared/build/bin/iosSimulatorArm64/debugFramework
            - $(PROJECT_DIR)/Frameworks
          HEADER_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/Frameworks/Python.xcframework/ios-arm64/Python.framework/Headers
            - $(PROJECT_DIR)/Frameworks/CIRISVerify.xcframework/ios-arm64/CIRISVerify.framework/Headers
          HEADER_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/Frameworks/Python.xcframework/ios-arm64_x86_64-simulator/Python.framework/Headers
            - $(PROJECT_DIR)/Frameworks/CIRISVerify.xcframework/ios-arm64-simulator/CIRISVerify.framework/Headers
          OTHER_LDFLAGS[sdk=iphoneos*]:
            - $(inherited)
            - "-force_load"
            - "$(PROJECT_DIR)/Frameworks/CIRISVerify.xcframework/ios-arm64/CIRISVerify.framework/CIRISVerify"
          OTHER_LDFLAGS[sdk=iphonesimulator*]:
            - $(inherited)
            - "-force_load"
            - "$(PROJECT_DIR)/Frameworks/CIRISVerify.xcframework/ios-arm64-simulator/CIRISVerify.framework/CIRISVerify"
        Release:
          FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/../shared/build/bin/iosArm64/releaseFramework
            - $(PROJECT_DIR)/Frameworks
          FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/../shared/build/bin/iosSimulatorArm64/releaseFramework
            - $(PROJECT_DIR)/Frameworks
          HEADER_SEARCH_PATHS[sdk=iphoneos*]:
            - $(inherited)
            - $(PROJECT_DIR)/Frameworks/Python.xcframework/ios-arm64/Python.framework/Headers
            - $(PROJECT_DIR)/Frameworks/CIRISVerify.xcframework/ios-arm64/CIRISVerify.framework/Headers
          HEADER_SEARCH_PATHS[sdk=iphonesimulator*]:
            - $(inherited)
            - $(PROJECT_DIR)/Frameworks/Python.xcframework/ios-arm64_x86_64-simulator/Python.framework/Headers
            - $(PROJECT_DIR)/Frameworks/CIRISVerify.xcframework/ios-arm64-simulator/CIRISVerify.framework/Headers
          OTHER_LDFLAGS[sdk=iphoneos*]:
            - $(inherited)
            - "-force_load"
            - "$(PROJECT_DIR)/Frameworks/CIRISVerify.xcframework/ios-arm64/CIRISVerify.framework/CIRISVerify"
          OTHER_LDFLAGS[sdk=iphonesimulator*]:
            - $(inherited)
            - "-force_load"
            - "$(PROJECT_DIR)/Frameworks/CIRISVerify.xcframework/ios-arm64-simulator/CIRISVerify.framework/CIRISVerify"
    dependencies:
      - framework: Frameworks/Python.xcframework
        embed: true
      - framework: Frameworks/CIRISVerify.xcframework
        embed: false
      - sdk: AuthenticationServices.framework
      - sdk: Security.framework
    preBuildScripts:
      - name: Link KMP Shared Framework
        script: |
          # Link the correct shared.framework based on configuration and SDK
          SHARED_FRAMEWORK_DIR="${PROJECT_DIR}/../shared/build/bin"

          echo "DEBUG: SDKROOT=$SDKROOT"
          echo "DEBUG: PLATFORM_NAME=$PLATFORM_NAME"
          echo "DEBUG: EFFECTIVE_PLATFORM_NAME=$EFFECTIVE_PLATFORM_NAME"
          echo "DEBUG: CONFIGURATION=$CONFIGURATION"

          # Determine architecture (device vs simulator)
          # Use PLATFORM_NAME which is more reliable for archive builds
          if [ "$PLATFORM_NAME" = "iphoneos" ] || [[ "$SDKROOT" == *"iphoneos"* ]]; then
            ARCH="iosArm64"
          else
            ARCH="iosSimulatorArm64"
          fi

          # Determine build type
          if [ "$CONFIGURATION" = "Release" ]; then
            BUILD_TYPE="releaseFramework"
          else
            BUILD_TYPE="debugFramework"
          fi

          echo "DEBUG: Selected ARCH=$ARCH BUILD_TYPE=$BUILD_TYPE"

          FRAMEWORK_PATH="${SHARED_FRAMEWORK_DIR}/${ARCH}/${BUILD_TYPE}/shared.framework"

          if [ ! -d "$FRAMEWORK_PATH" ]; then
            echo "error: shared.framework not found at $FRAMEWORK_PATH"
            echo "Run: cd mobile && ./gradlew :shared:linkReleaseFrameworkIosArm64"
            exit 1
          fi

          # Copy framework to build directory for embedding
          DEST_PATH="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/shared.framework"
          rm -rf "$DEST_PATH"
          cp -R "$FRAMEWORK_PATH" "$DEST_PATH"

          # Fix shared.framework Info.plist for App Store compliance
          PLIST="${DEST_PATH}/Info.plist"
          if [ -f "$PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 15.0" "$PLIST" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier ai.ciris.mobile.shared" "$PLIST" 2>/dev/null || true
            echo "Fixed shared.framework Info.plist"
          fi

          echo "Embedded shared.framework from: $FRAMEWORK_PATH"
        basedOnDependencyAnalysis: false
    postCompileScripts:
      - name: Embed Python Native Modules
        script: "${PROJECT_DIR}/scripts/embed_native_frameworks.sh"
        basedOnDependencyAnalysis: false

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
