services:
  # CIRIS GUI in development mode with hot reload
  gui:
    image: node:20-alpine
    container_name: ciris-gui-dev
    working_dir: /app
    volumes:
      - ../CIRISGUI/apps/agui:/app
    environment:
      - NEXT_PUBLIC_CIRIS_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
