services:
  ciris:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    container_name: ciris
    env_file:
      - ${CIRIS_ENV_FILE:-../.env}
    ports:
      - "8080:8080"
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    # Note: --host 0.0.0.0 is required in Docker containers to bind to all interfaces
    # within the container, allowing access from the Docker host. The host's firewall
    # and Docker's port mapping provide security. For non-Docker deployments, use 127.0.0.1
    command: ["python", "main.py", "--adapter", "api", "--host", "0.0.0.0", "--port", "8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
