version: '3.8'

# Production deployment with separate .env files per agent
# Usage: docker-compose -f docker-compose.production.yml up -d

services:
  # Agent Datum (Primary decision-making)
  agent-datum:
    image: ghcr.io/cirisai/ciris-agent:latest
    container_name: ciris-agent-datum
    expose:
      - "8080"
    env_file:
      - ../.env.datum
    environment:
      - CIRIS_API_HOST=0.0.0.0
      - CIRIS_API_PORT=8080
      - CIRIS_ADAPTER=api
      - CIRIS_MOCK_LLM=true
    volumes:
      - datum_data:/app/data
      - datum_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ciris-network

  # Agent Sage (Wisdom and deep analysis)
  agent-sage:
    image: ghcr.io/cirisai/ciris-agent:latest
    container_name: ciris-agent-sage
    expose:
      - "8081"
    env_file:
      - ../.env.sage
    environment:
      - CIRIS_API_HOST=0.0.0.0
      - CIRIS_API_PORT=8081
      - CIRIS_ADAPTER=api
      - CIRIS_MOCK_LLM=true
    volumes:
      - sage_data:/app/data
      - sage_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ciris-network

  # Agent Scout (Information gathering and reconnaissance)
  agent-scout:
    image: ghcr.io/cirisai/ciris-agent:latest
    container_name: ciris-agent-scout
    expose:
      - "8082"
    env_file:
      - ../.env.scout
    environment:
      - CIRIS_API_HOST=0.0.0.0
      - CIRIS_API_PORT=8082
      - CIRIS_ADAPTER=api
      - CIRIS_MOCK_LLM=true
    volumes:
      - scout_data:/app/data
      - scout_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ciris-network

  # Agent Echo-Core (Core reasoning and consistency)
  agent-echo-core:
    image: ghcr.io/cirisai/ciris-agent:latest
    container_name: ciris-agent-echo-core
    expose:
      - "8083"
    env_file:
      - ../.env.echo-core
    environment:
      - CIRIS_API_HOST=0.0.0.0
      - CIRIS_API_PORT=8083
      - CIRIS_ADAPTER=api
      - CIRIS_MOCK_LLM=true
    volumes:
      - echo_core_data:/app/data
      - echo_core_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ciris-network

  # Agent Echo-Speculative (Speculative reasoning and possibilities)
  agent-echo-speculative:
    image: ghcr.io/cirisai/ciris-agent:latest
    container_name: ciris-agent-echo-speculative
    expose:
      - "8084"
    env_file:
      - ../.env.echo-speculative
    environment:
      - CIRIS_API_HOST=0.0.0.0
      - CIRIS_API_PORT=8084
      - CIRIS_ADAPTER=api
      - CIRIS_MOCK_LLM=true
    volumes:
      - echo_speculative_data:/app/data
      - echo_speculative_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ciris-network

  # GUI Application
  ciris-gui:
    image: ghcr.io/cirisai/ciris-gui:latest
    container_name: ciris-gui
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DATUM_URL=https://agents.ciris.ai
      - NEXT_PUBLIC_SAGE_URL=https://agents.ciris.ai/api/sage
      - NEXT_PUBLIC_SCOUT_URL=https://agents.ciris.ai/api/scout
      - NEXT_PUBLIC_ECHO_CORE_URL=https://agents.ciris.ai/api/echo-core
      - NEXT_PUBLIC_ECHO_SPEC_URL=https://agents.ciris.ai/api/echo-speculative
    restart: unless-stopped
    networks:
      - ciris-network

volumes:
  datum_data:
  datum_logs:
  sage_data:
  sage_logs:
  scout_data:
  scout_logs:
  echo_core_data:
  echo_core_logs:
  echo_speculative_data:
  echo_speculative_logs:

networks:
  ciris-network:
    driver: bridge