version: "1.0"
log_level: "INFO"
database:
  db_filename: "ciris_engine.db"
  data_directory: "data"
  graph_memory_filename: "graph_memory.pkl"
llm_services:
  openai:
    model_name: "gpt-4o-mini"
    base_url: null
    timeout_seconds: 30.0
    max_retries: 3
    api_key_env_var: "OPENAI_API_KEY"
    instructor_mode: "JSON"
workflow:
  max_active_tasks: 10
  max_active_thoughts: 50
  round_delay_seconds: 1.0
  max_rounds: 5
  DMA_RETRY_LIMIT: 3
  GUARDRAIL_RETRY_LIMIT: 2
guardrails: {}
profile_directory: "ciris_profiles"
default_profile: "default"
agent_profiles: {}
