#!/usr/bin/env python3
"""Generate obfuscated _build_secrets.py for iOS builds.

Same XOR obfuscation as Android's build.gradle generatePythonSecrets task.
Reads from ~/.<key_name> files and generates the secrets Python module.

Usage:
    python3 tools/generate_ios_secrets.py
    # Output: client/iosApp/Resources/app/ciris_adapters/wallet/providers/_build_secrets.py
"""

import os
from pathlib import Path

# XOR key (same as Android)
XOR_KEY = [0x5A, 0x3C, 0x7E, 0x1F, 0x9B, 0x4D, 0x2E, 0x6A]

# Secrets: function_name -> source_file
SECRETS = {
    "arka_api_key": os.path.expanduser("~/.etherspot_android_key"),
    "coinbase_paymaster_url": os.path.expanduser("~/.coinbase_paymaster_url"),
}


def obfuscate(value: str) -> list[int]:
    return [ord(ch) ^ XOR_KEY[i % len(XOR_KEY)] for i, ch in enumerate(value)]


def main():
    obfuscated = {}
    for name, filepath in SECRETS.items():
        p = Path(filepath)
        if p.exists():
            value = p.read_text().strip()
            obfuscated[name] = obfuscate(value)
            print(f"  Found: {name} from {filepath}")
        else:
            obfuscated[name] = []
            print(f"  WARNING: {filepath} not found — {name} will be empty")

    # Generate getter functions
    getters = []
    for name, data in obfuscated.items():
        getters.append(
            f'''
def get_{name}() -> str:
    """Get {name} (obfuscated at build time)."""
    data = {data}
    if not data:
        return ""
    return _deobfuscate(data, _XK)
'''
        )

    available = "\n".join(f"  - get_{name}()" for name in obfuscated)

    content = f'''"""
Build-time generated secrets - DO NOT EDIT OR COMMIT.
Generated by tools/generate_ios_secrets.py

Available functions:
{available}
"""
from typing import Optional


def _deobfuscate(data: list, key: list) -> str:
    """Deobfuscate XOR-encoded data."""
    return ''.join(chr(d ^ key[i % len(key)]) for i, d in enumerate(data))


_XK = [0x5A, 0x3C, 0x7E, 0x1F, 0x9B, 0x4D, 0x2E, 0x6A]
{"".join(getters)}'''

    # Write to iOS Resources AND local ciris_adapters
    outputs = [
        Path("client/iosApp/Resources/app/ciris_adapters/wallet/providers/_build_secrets.py"),
        Path("ciris_adapters/wallet/providers/_build_secrets.py"),
    ]

    for out in outputs:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content)
        print(f"  Generated: {out}")

    print(f"\nDone — {len(obfuscated)} secrets obfuscated")


if __name__ == "__main__":
    main()
