"""CIRISVerify thread runner for attestation.

This module handles running CIRISVerify on a separate thread with a larger
stack size, as required by Rust Tokio compatibility.
"""

import asyncio
import logging
import os
import sys
import threading
from contextlib import asynccontextmanager
from typing import Any, AsyncGenerator, Callable, Dict, Optional

from .hashes import load_python_hashes

# Python 3.10 compatibility: asyncio.timeout was added in Python 3.11
if sys.version_info >= (3, 11):
    _async_timeout = asyncio.timeout
else:

    @asynccontextmanager
    async def _async_timeout(delay: float) -> AsyncGenerator[None, None]:
        """Python 3.10 compatible timeout context manager."""
        loop = asyncio.get_event_loop()
        task = asyncio.current_task()
        if task is None:
            raise RuntimeError("No current task")

        timed_out = False

        def timeout_callback() -> None:
            nonlocal timed_out
            timed_out = True
            task.cancel()  # type: ignore[union-attr]

        handle = loop.call_later(delay, timeout_callback)
        try:
            yield
        except asyncio.CancelledError:  # noqa: ASYNC910  # NOSONAR
            # Cleanup: cancel the timeout callback
            handle.cancel()
            # Convert our own timeout-triggered cancellation to TimeoutError
            # (matches Python 3.11 asyncio.timeout behavior)
            if timed_out:
                raise asyncio.TimeoutError() from None
            # External cancellation - must re-raise per asyncio contract
            raise  # Re-raised for external cancellations (not our timeout)
        else:
            handle.cancel()


from .paths import find_audit_db_path, get_agent_root, get_ed25519_fingerprint
from .types import PythonHashesWrapper, VerifyThreadResult

logger = logging.getLogger(__name__)

# Timeout for attestation thread (seconds)
ATTESTATION_TIMEOUT = 90


def _get_verifier_version(verifier: Any) -> str:
    """Get CIRISVerify version.

    Args:
        verifier: CIRISVerify verifier instance

    Returns:
        Version string or "unknown"
    """
    try:
        version = getattr(verifier, "version", None)
        if callable(version):
            version = version()
        if version is None:
            import ciris_adapters.ciris_verify as ciris_verify

            version = getattr(ciris_verify, "__version__", "unknown")
        return str(version) if version else "unknown"
    except Exception as e:
        logger.warning(f"[attestation] Version check failed: {e}")
        return "unknown"


def _run_attestation_sync(
    verifier: Any,
    spot_check_count: int,
    attestation_mode: str,
    python_hashes: Optional[PythonHashesWrapper],
    agent_version: Optional[str],
    agent_root: str,
    key_fingerprint: Optional[str],
) -> Optional[Dict[str, Any]]:
    """Run synchronous attestation via CIRISVerify.

    Args:
        verifier: CIRISVerify verifier instance
        spot_check_count: Number of files to spot check (0 for full)
        attestation_mode: "full" or "partial"
        python_hashes: Python module hashes wrapper
        agent_version: Agent version string
        agent_root: Agent root directory path
        key_fingerprint: Ed25519 key fingerprint

    Returns:
        Attestation result dict or None
    """
    if not hasattr(verifier, "run_attestation_sync"):
        return None

    # Generate a random challenge nonce (required by CIRISVerify)
    challenge = os.urandom(32)

    logger.info(
        f"[attestation] Calling run_attestation_sync with "
        f"agent_root={agent_root}, agent_version={agent_version}, "
        f"python_hashes_count={python_hashes.module_count if python_hashes else 0}"
    )

    attestation_data: Dict[str, Any] = verifier.run_attestation_sync(
        challenge=challenge,
        spot_check_count=spot_check_count,
        partial_file_check=(attestation_mode == "partial"),
        python_hashes=python_hashes,
        agent_version=agent_version,
        agent_root=agent_root,
        key_fingerprint=key_fingerprint,
        portal_key_id=key_fingerprint,  # Same as key_fingerprint for signature verification
    )

    logger.info("[attestation] run_attestation_sync completed")
    _strip_build_time_files_from_integrity(attestation_data)
    return attestation_data


# Files whose hashes can't be pinned in the FFI's baked-at-build manifest because
# their content is generated/injected at runtime or per-build. Failures on these
# files are not tampering signals — they're build-config noise.
_BUILD_TIME_INJECTED_FILES = frozenset(
    {
        # Wallet provider secrets — generated by tools/generate_ios_secrets.py at
        # build time, contains per-build API keys/URLs. The FFI manifest pinned
        # one specific build's hash but every other build (and every dev install)
        # has a different hash by design.
        "ciris_adapters/wallet/providers/_build_secrets.py",
    }
)


def _strip_build_time_files_from_integrity(attestation_data: Dict[str, Any]) -> None:
    """Remove known build-time-injected files from the python_integrity result.

    These files have machine/build-specific hashes by design and should never
    have been in the FFI's hash manifest. Stripping them here prevents:
      - The conscience from reading ✗FileIntegrity and inventing tampering
        threats during action selection.
      - Spurious ATTESTATION_FAILURE incidents on every dev install.

    The actual list of failures is preserved in the audit log via the original
    FFI response — this only filters the result that propagates into the
    runtime context that the conscience consumes.
    """
    if not isinstance(attestation_data, dict):
        return
    py_int = attestation_data.get("python_integrity")
    if not isinstance(py_int, dict):
        return
    failed = py_int.get("failed_modules")
    if not isinstance(failed, dict) or not failed:
        return

    stripped = {k: v for k, v in failed.items() if k not in _BUILD_TIME_INJECTED_FILES}
    if len(stripped) == len(failed):
        return  # Nothing to strip

    n_stripped = len(failed) - len(stripped)
    py_int["failed_modules"] = stripped
    py_int["modules_failed"] = max(0, py_int.get("modules_failed", 0) - n_stripped)
    py_int["modules_passed"] = py_int.get("modules_passed", 0) + n_stripped
    if not stripped:
        py_int["valid"] = True
        py_int.pop("error", None)
    logger.info(
        f"[attestation] Stripped {n_stripped} build-time-injected file(s) from "
        f"python_integrity failed_modules; new modules_failed={py_int['modules_failed']}, "
        f"valid={py_int['valid']}"
    )


def _verify_audit_trail(
    verifier: Any,
    audit_db_path: str,
    key_fingerprint: Optional[str],
    attestation_data: dict[str, Any],
) -> dict[str, Any]:
    """Verify audit trail and merge results.

    Args:
        verifier: CIRISVerify verifier instance
        audit_db_path: Path to audit database
        key_fingerprint: Ed25519 key fingerprint
        attestation_data: Existing attestation data to merge into

    Returns:
        Updated attestation data with audit trail results
    """
    if not hasattr(verifier, "verify_audit_trail_sync"):
        return attestation_data

    try:
        logger.info(f"[attestation] Calling verify_audit_trail_sync with db_path={audit_db_path}")
        audit_result = verifier.verify_audit_trail_sync(
            db_path=audit_db_path,
            portal_key_id=key_fingerprint,
        )
        logger.info(f"[attestation] Audit trail verification result: {audit_result}")

        if audit_result:
            attestation_data["audit_trail"] = audit_result

    except Exception as e:
        logger.warning(f"[attestation] verify_audit_trail_sync failed: {e}")

    return attestation_data


def _log_attestation_response(attestation_data: Optional[dict[str, Any]]) -> None:
    """Log raw attestation response for debugging.

    Args:
        attestation_data: Attestation response dict
    """
    logger.info(f"[attestation] Raw response keys: {list(attestation_data.keys()) if attestation_data else 'None'}")
    if attestation_data:
        logger.info(f"[attestation] level={attestation_data.get('level')}, valid={attestation_data.get('valid')}")
        logger.info(f"[attestation] sources={attestation_data.get('sources')}")
        logger.info(f"[attestation] key_attestation={attestation_data.get('key_attestation')}")
        logger.info(f"[attestation] python_integrity={attestation_data.get('python_integrity')}")
        logger.info(f"[attestation] self_verification={attestation_data.get('self_verification')}")
        logger.info(f"[attestation] file_integrity={attestation_data.get('file_integrity')}")
        logger.info(f"[attestation] audit_trail={attestation_data.get('audit_trail')}")


def create_verification_thread_target(
    get_verifier: Callable[[], Any],
    attestation_mode: str,
    result_container: VerifyThreadResult,
) -> Callable[[], None]:
    """Create the target function for the verification thread.

    Args:
        get_verifier: Function to get the verifier instance
        attestation_mode: "full" or "partial"
        result_container: Container to store results

    Returns:
        Thread target function
    """
    spot_check_count = 0 if attestation_mode == "full" else 10

    def _run_verify_on_large_stack() -> None:
        """Run CIRISVerify on a thread with larger stack (Rust Tokio compatibility)."""
        try:
            verifier = get_verifier()
            if verifier is None:
                result_container.error = "CIRISVerify singleton not available"
                return

            version = _get_verifier_version(verifier)

            # Load Python hashes
            python_hashes, agent_version = load_python_hashes()

            # Get paths and fingerprint
            agent_root = get_agent_root()
            key_fingerprint = get_ed25519_fingerprint(verifier)
            audit_db_path = find_audit_db_path()

            # Run attestation
            attestation_data = _run_attestation_sync(
                verifier=verifier,
                spot_check_count=spot_check_count,
                attestation_mode=attestation_mode,
                python_hashes=python_hashes,
                agent_version=agent_version,
                agent_root=agent_root,
                key_fingerprint=key_fingerprint,
            )

            if attestation_data is None:
                attestation_data = {"error": "run_attestation_sync not available"}

            # Verify audit trail if we have a DB path
            if audit_db_path and attestation_data:
                attestation_data = _verify_audit_trail(verifier, audit_db_path, key_fingerprint, attestation_data)

            _log_attestation_response(attestation_data)

            result_container.result = {
                "version": version,
                "attestation": attestation_data,
            }

        except ImportError as e:
            result_container.error = f"CIRISVerify not available: {e}"
        except Exception as e:
            result_container.error = f"Attestation error: {e}"

    return _run_verify_on_large_stack


async def run_verification_thread(
    get_verifier: Callable[[], Any],
    attestation_mode: str,
) -> VerifyThreadResult:
    """Run CIRISVerify attestation in a separate thread.

    This function runs attestation on a thread with a larger stack size
    (required by Rust Tokio) and polls for completion asynchronously.

    Args:
        get_verifier: Function to get the verifier instance
        attestation_mode: "full" or "partial"

    Returns:
        VerifyThreadResult with result or error
    """
    result = VerifyThreadResult()

    thread_target = create_verification_thread_target(get_verifier, attestation_mode, result)

    # Run on thread with 8MB stack (Rust Tokio requirement)
    thread = threading.Thread(target=thread_target, daemon=True)
    thread.start()

    # Non-blocking wait: poll thread status while yielding to event loop
    # Use _async_timeout for Python 3.10 compatibility
    try:
        async with _async_timeout(ATTESTATION_TIMEOUT):
            while thread.is_alive():
                await asyncio.sleep(0.1)  # Yield to event loop every 100ms
    except asyncio.TimeoutError:
        logger.warning(f"[attestation] TIMEOUT: Thread still alive after {ATTESTATION_TIMEOUT} seconds!")
        result.error = f"Attestation timed out after {ATTESTATION_TIMEOUT} seconds"

    return result
